CREATE USER ogdemo IDENTIFIED BY ogdemo
   DEFAULT TABLESPACE users
   TEMPORARY TABLESPACE temp
   QUOTA UNLIMITED ON users;
GRANT CONNECT, RESOURCE to ogdemo;
GRANT CREATE VIEW to ogdemo;
GRANT SELECT_CATALOG_ROLE to ogdemo;
GRANT SELECT ANY DICTIONARY to ogdemo;
GRANT INHERIT PRIVILEGES ON USER ogdemo TO PUBLIC; -- 12c only
